version: "3.8"

services:
  anami-backend:
    build: .
    container_name: anami_backend
    restart: always
    ports:
      - "4001:3000" # Exponemos el 4000 externo -> 3000 interno
    environment:
      # Conexi√≥n a la red interna (nombres de contenedores)
      DATABASE_URL: "postgresql://anami:pass@postgres_core_server:5432/anami_masoterapia"
      NODE_ENV: "production"
    networks:
      - infra_network

networks:
  infra_network:
    external: true
    name: infra_network
