name: Deploy Backend

on:
  push:
    branches: ["main"]
    paths:
      - "src/**"
      - "prisma/**"
      - "package.json"
      - "Dockerfile"
      - ".github/workflows/deploy-backend.yml"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 1. Login en Docker Hub
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # 2. Configurar Buildx (Necesario para compilar ARM64 en GitHub)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Construir y Subir Imagen
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ikedaharket/anami-backend:latest
            ikedaharket/anami-backend:${{ github.sha }}
          platforms: linux/amd64,linux/arm64

      # 4. Desplegar en Raspberry Pi vía SSH
      - name: Deploy to Raspberry Pi
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker pull ikedaharket/anami-backend:latest

            if [ "$(docker ps -aq -f name=anami_backend)" ]; then
                docker stop anami_backend
                docker rm anami_backend
            fi

            docker run -d \
              --name anami_backend \
              --restart always \
              --network infra_network \
              -p 4001:3000 \
              -e NODE_ENV=production \
              -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
              -e API_PUBLIC_PATH="/anami" \
              -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
              -e LOGGER_SERVICE_URL="http://ikedadev_logger:4002/v1/ingest" \
              -e LOGGER_API_KEY="${{ secrets.LOGGER_API_KEY }}" \
              ikedaharket/anami-backend:latest

            # Limpiar imágenes viejas
            docker image prune -f
